### PR TITLE
Move Maps

### PR DESCRIPTION
**Pull request by FourOne**

### CODE REVIEW

**Comment by dreadflopp** [comment]
I was meant to fix this conflict but actually forgot about it. If you use the suggested version of A quality world map, there shouldn't be any conflicts with the output from xLODGen, but I will check again. My suggested solution for the conflict with the Falskaar/Wyrmstooth maps is to delete the files from the xLODGen output, it is about 5-10 files, rather than moving Better Falskaar and Wyrmstooth Map With Roads.

**Comment by FourOne** [comment]
Falskaar/Wyrmstooth Maps are still overwritten by Falskaar/Wyrmstooth itself, i just made sure i get the right maps in the end (stolen from lexys guide, but this guide is also using v.9). But of course u can just delete/hide files.

**Comment by dreadflopp** [comment]
The maps shouldn't be overwritten by Falskaar/Wyrmtooth since the maps are loose files, which takes precedence over bsa's. But that also makes me realise that the loose files from xLODGen output overwrites the bsa from A Quality World map. I will fix this tomorrow by listing the files from xLODGen output that should be deleted.

**Comment by FourOne** [comment]
Ahh sry, i forgot that i unpack all bsa on default - old habit. But you are right, then its ok 2 just delete the xLODGen output.

**Pull request closed without merging**
